apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: movie 
spec:
  type: ClusterIP
  replicas: 3
  template:
    metadata:
      labels:
        app: movie 
    spec:
      containers:
        - name: movie 
          image: admin9.azurecr.io/movie
          ports:
          - containerPort: 8080
